language: python

env:
  - TOXENV=py25
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34

os:
  - linux

install:
  - pip install tox
  - pip install coveralls

script: 
  - tox
  - python setup.py test --addopts "-v --cov simplesqlite --cov-report term-missing"

after_success:
  - coveralls
